let num = 10;
console.log(num);
let first = 5;
let second = 10;
console.log(first+second);
console.log(first-second);
console.log(first*second);
console.log(first/second);
let a = 3;
let b = 10;
let result = a+b;
let bar = 20;
let qwerty = 5;
let res = bar-qwerty-10;
let end = res-qwerty;
let str = ('Hello, Palmo');
alert(str)
let name = ('Вячеслав');
let age = ('36');
alert(`Я ${name}, мне ${age}`)
let huor = 60*60;
let day = 60*60*24;
let month = 60*60*24*30;
console.log(huor);
console.log(day);
console.log(month);
let c = 6;
c **= 2;
let n = 8;
let d = n;
d **= 2;
let x = d;
x **= 3;
let palmo1 = "Hello, Palmo";
alert(palmo1);
let palmo2 = 'Hello, Palmo';
alert(palmo2);
let palmo3 = ('Palmo');
alert(`Hello, ${palmo3}`);
let youName = prompt('Ввидите ваше имя','Bob');
let question = confirm('Я все сделал правильно?');
alert(question);
let noNamb = '12345';
let namb = Number(noNamb);
let noStr = true;
let yesStr = String(noStr);
alert(Boolean(0));
alert(Boolean(''));

